In [13]:
# Final Exam - Question 1 - Maxwell Martin

import numpy as np

# a.
ar1 = np.arange(15).reshape(5,3)
ar1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [14]:
# b.
ar1 = ar1 + 5
ar1

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [15]:
# c.
ar1[1:3, 1:]

array([[ 9, 10],
       [12, 13]])

In [16]:
# d.
ar1[-1, 0] = 25
ar1[0:,0]

array([ 5,  8, 11, 14, 25])

In [17]:
# e.
ar2 = np.random.randint(40,120,size=(3,4))
ar2

array([[ 70,  78,  42, 100],
       [ 73,  51, 106,  82],
       [ 59,  86,  52,  95]])

In [18]:
# f.
ar2 = ar2.astype(np.float)

In [19]:
ar2.dtype

dtype('float64')

In [20]:
# g.
ar2.min()

42.0

In [21]:
ar2.max()

106.0