In [ ]:
import numpy as np

In [72]:
# Practice Problem 1

# Create a numpy array with random numbers from 0 to 11 (both included). 
# The shape of the array should be 3 rows and 4 columns.
# Display the array.
arr = np.random.randint(0,12, size = (3,4))
print(arr)

[[ 4  7 11  2]
 [ 2  5  3  8]
 [ 9  8 10  1]]


In [73]:
# 1)
arr.size

12

In [74]:
# 2)
arr[1:,:]

array([[ 2,  5,  3,  8],
       [ 9,  8, 10,  1]])

In [75]:
# 3)
arr[1,-3:]

array([5, 3, 8])

In [76]:
# 4)
arr * 3

array([[12, 21, 33,  6],
       [ 6, 15,  9, 24],
       [27, 24, 30,  3]])

In [77]:
# 5)
arr[2,3] = 98
print(arr)

[[ 4  7 11  2]
 [ 2  5  3  8]
 [ 9  8 10 98]]


In [78]:
# 6)
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))

167
2
98


In [80]:
# 7)
arr = arr.astype(np.float)
print(arr)
arr.dtype

[[ 4.  7. 11.  2.]
 [ 2.  5.  3.  8.]
 [ 9.  8. 10. 98.]]


dtype('float64')

In [22]:
# Practice Problem 2

import csv

# a)
infile = open("athletes.csv")
reader = csv.reader(infile)
count = 1
for row in reader:
    if count > 5:
        break
    print(row)
    count += 1
infile.close()

['id', 'name', 'nationality', 'sex', 'date_of_birth', 'age', 'height', 'weight', 'sport', 'gold', 'silver', 'bronze']
['736041664', 'A Jesus Garcia', 'ESP', 'male', '10/17/1969', '30', '1.72', '64', 'athletics', '0', '0', '0']
['532037425', 'A Lam Shin', 'KOR', 'female', '9/23/1986', '24', '1.68', '56', 'fencing', '0', '0', '0']
['435962603', 'Aaron Brown', 'CAN', 'male', '5/27/1992', '23', '1.98', '79', 'athletics', '0', '0', '1']
['521041435', 'Aaron Cook', 'MDA', 'male', '1/2/1991', '23', '1.83', '80', 'taekwondo', '0', '0', '0']


In [29]:
# b)
regular_arr = []
infile = open("athletes.csv")
reader = csv.reader(infile)
for row in reader:
    regular_arr.append(row)
infile.close()
arr = np.array(regular_arr)
print(arr)
print(type(arr))
print(arr.shape)

[['id' 'name' 'nationality' ... 'gold' 'silver' 'bronze']
 ['736041664' 'A Jesus Garcia' 'ESP' ... '0' '0' '0']
 ['532037425' 'A Lam Shin' 'KOR' ... '0' '0' '0']
 ...
 ['88361042' 'di Xiao' 'CHN' ... '0' '0' '0']
 ['900065925' 'le Quoc Toan Tran' 'VIE' ... '0' '0' '0']
 ['711404576' 'le Roux Hamman' 'RSA' ... '0' '0' '0']]
<class 'numpy.ndarray'>
(11539, 12)


In [38]:
# c)
arr[2,7] = 60
print(arr[2,7])

60
